app/models.py
from . import db,login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin,current_user


class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    pass_secure = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    blog = db.relationship('Blog',backref='user', lazy='dynamic')
    comment = db.relationship('Comment', backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)
    
    def __repr__(self):
        return f'User {self.username}'


class Blog(db.Model):
     __tablename__ = 'blog'
     id = db.Column(db.Integer,primary_key = True)
     username = db.Column(db.String(255),index = True)
     blog = db.Column(db.String(300),index =True)
     title = db.Column(db.String(100), index = True)
     user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
     comment = db.relationship('Comment', backref='pitch', lazy='dynamic')

     def save_p(self):
        db.session.add(self)
        db.session.commit()

     def delete(self):
        db.session.delete(self)
        db.session.commit()

     def get_blog(id):
        blog = Blog.query.filter_by(id=id).first()
        return blog

     def __repr__(self):
        return f'Blog {self.title}'

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.Text(),nullable = False)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable = False)
    blog_id = db.Column(db.Integer,db.ForeignKey('blog.id'),nullable = False)
    

    def save_c(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.remove(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,blog_id):
        comments = Comment.query.filter_by(blog_id=blog_id).all()
        return comments

    
    def __repr__(self):
        return f'comment:{self.comment}'
    
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired


class CreateBLog(FlaskForm):
    name = StringField('Your Name',validators=[DataRequired()])
    title = StringField('Title',validators =[DataRequired()])
    blog = TextAreaField('Blog',validators =[DataRequired()])
    submit = SubmitField('Submit Blog')

class CommentForm(FlaskForm):
    comment = TextAreaField('Leave a comment',validators=[DataRequired()])
    submit = SubmitField('Comment')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import DevConfig,config_options,Config
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

# Initializing application
bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
# Initializing application
    app = Flask(__name__)


    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    app.config.from_object(config_options[config_name])
    app.config.from_object(DevConfig)
    app.config.from_object(Config)
    
    app.config['SECRET_KEY'] = '1234'
    app.config['SQLALCHEMY_DATABASE_URI']= 'postgresql://uvwvmkiqhgfubf:abe513190f4f7f07835a812186460cc53c065e6e4ace40ddaf28182a21fc02af@ec2-54-86-224-85.compute-1.amazonaws.com:5432/d7i76dml2jcpeh'


    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from  . import views,forms

app/main/views.py
from app.request import get_quotes
from . import main
from flask import render_template,redirect,url_for,abort,flash,request
from flask_login import current_user, login_required
from .forms import CreateBLog,UpdateProfile,CommentForm
from ..models import User,Blog,Comment
from .. import db

@main.route('/')
def index():
   return render_template('index.html')

@main.route('/home')
@login_required
def home():
   return render_template('home.html')

@main.route('/random_quotes')
@login_required
def random():
   quote = get_quotes()
   return render_template('random.html',quote = quote)


@main.route('/create_new', methods = ['POST','GET'])
@login_required
def new_blog():
    form =CreateBLog()
    if form.validate_on_submit():
        title = form.title.data
        blog = form.blog.data
        name = form.name.data
        new_pitch_object = Blog(username=name,user_id=current_user._get_current_object().id,blog=blog,title=title)
        new_pitch_object.save_p()
        return redirect(url_for('main.blog'))
        
    return render_template('blog.html', form = form)

@main.route('/blog')
@login_required
def blog():
    blog = Blog.query.all()
    return render_template('new_blog.html', blog = blog)

@main.route('/blog/<blog_id>/update', methods = ['GET','POST'])
@login_required
def updateblog(blog_id):
    blog = Blog.query.get(blog_id)
    if blog.user != current_user:
        abort(403)
    form = CreateBLog()
    if form.validate_on_submit():
        blog.username = form.name.data
        blog.title = form.title.data
        blog.blog = form.blog.data
        db.session.commit()
        flash("You have updated your Blog!")
        return redirect(url_for('main.blog',id = blog.id)) 
    if request.method == 'GET':
        form.name.data = blog.username
        form.title.data = blog.title
        form.blog.data = blog.blog
    return render_template('blog.html', form = form)

@main.route('/blog/<blog_id>/delete', methods = ['POST'])
def delete_post(blog_id):
    blog = Blog.query.get(blog_id)
    if blog.user != current_user:
        abort(403)
    blog.delete()

    flash("You have deleted your Blog succesfully!")
    return redirect(url_for('main.blog'))


@main.route('/comment/<int:blog_id>', methods = ['POST','GET'])
def comment(blog_id):
    form = CommentForm()
    blog = Blog.query.get(blog_id)
    all_comments = Comment.query.filter_by(blog_id = blog_id).all()
    if form.validate_on_submit():
        comment = form.comment.data 
        blog_id = blog_id
        user_id = current_user._get_current_object().id
        new_comment = Comment(comment = comment,user_id = user_id,blog_id = blog_id)
        new_comment.save_c()
        return redirect(url_for('.comment', blog_id = blog_id))
    return render_template('comment.html', form =form, blog = blog,all_comments=all_comments)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('main.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

app/templates/base.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{{url_for('static',filename='index.css')}}">

{% extends 'bootstrap/base.html'%}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/blog.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container">
<div class="row">
<div class="col-md-2"> </div>
<div class="col-md-8" style="font-size: 20px;">

{{wtf.quick_form(form)}}

</div>
<div class="col-md-2"></div>
</div>
</div>

{% endblock%}

app/templates/comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container" id="allcomments" >
        <div class="row">

            {% if all_comments %}
                <div class="col-md-7" >
                    <h3 class="text-center" id="coms">All comments for the post</h3>
                    {% for comment in all_comments %}
                       <div class="card w-90 mb-3" >
                           <div class="card-body">
                            <h5>{{comment.pitch.title}}</h5>
                             <p class="card-title">{{ comment.comment }}</p>
                             <p class="card-text">--- {{comment.user.username}}</p>
                           </div>
                       </div>
                    {% endfor %}
                   </div>
                   <div class="col-md-5  commentform" >

                        {{wtf.quick_form(form)}}
                   </div>
               </div>
            {%else%}
            <div class="card w-90 mb-3">
                <div class="card-body">
                  <p class="card-title">No Comments for this yet for this post. Be the first to comment</p>
                </div>
            </div> 
            <div class="col-md-5">
                    {{wtf.quick_form(form)}}
                </div>
            {%endif%}
    </div>
   
{% endblock%}

app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<section>
    <h2>Save the moments that matter. This site lets you safely store thousands of posts.
        Write daily blogs that are unique to be displayed to your audience.
    </h2>
</section>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/index.css">
    <title>Document</title>
</head>
<body>
    <div class="center">
        <div class="title">Create Your own Blog</div>
        <div class="sub_title">Inspire others</div>
        <div class="btns">
          <button> <a href="{{url_for('auth.login')}}" class="navbar-brand" style="font-size: 25px;text-decoration: none;color: black;">Login</a></button>
          <button> <a href="{{url_for('auth.register')}}" class="navbar-brand" style="font-size: 25px;text-decoration:none; color: white;">Signup</a></button>
        </div>
      </div>
</body>
</html>
 

app/templates/navbar.html
<nav class="navbar navbar-inverse" role="navigation" style="font-size: x-large;">
    <a href="{{url_for('main.home')}}" class="navbar-brand" style="font-size: 25px;">Home</a> 
  
      
      <a href="{{url_for('main.new_blog')}}" class="navbar-brand" style="font-size: 25px;">Create Blog</a>
      <a href="{{url_for('main.blog')}}" class="navbar-brand" style="font-size: 25px;">View Blog</a>
      <a href="{{url_for('main.random')}}" class="navbar-brand" style="font-size: 25px;">Random Quote</a>

      <div class="dropdown" style="font-size: x-large;">
        <a class="btn btn-primary dropdown-toggle" style="width: 150px; font-size: 25px;" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          Account
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="font-size: 25px;">
          <li><a class="dropdown-item" href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
          <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">Sign out</a></li>
        </ul>
      </div>
</nav>

app/templates/new_blog.html
{% extends 'base.html'%}
{% block content %}

{% for message in get_flashed_messages() %}
<div class="alert alert-success">
<button type="button" class="close" data-dismiss="alert">&times;</button>
{{ message }}
</div>
{% endfor %}

<div class="container-fluid landing">
    <div class="row">
                {% for blog in blog %}
                <div class="col-md-4 d-flex jusify-content-center" style="margin: 1%; width: 500px;">
                    <div class="card" style="background-color:whitesmoke;">
                        <h5 style="color:black; font-size:30px;" class="card-header">{{blog.title}}</h5>
                        <div class="card-body">
                                <p style="font-size: 40px;">{{blog.blog}}</p>
                                <footer class="blockquote-footer text-center" > Posted by: {{blog.username}}</footer>
                                
                                <span class="foot" >{{blog.comment.count()}} Comments</span>
                                    <a href="{{url_for('main.comment',blog_id = blog.id)}}" class="btn btn-primary"> Comment</a>
                                    {% if blog.user == current_user %}
                                    <div class="yo" style="float: right;">
                                        <a  class="btn btn-info btn-sm m-1" href="{{url_for('main.updateblog',blog_id = blog.id)}}">Edit Blog</a>
                                    </div>
                                    <div class="yo" style="float: right;">
                                        <form action="{{url_for('main.delete_post',blog_id = blog.id)}}" method="POST">
                                            <input  type="submit" class="btn  btn-primary" value="Delete Post">
                                        </form>
                                    
                                    </div>
                    
                                    {% endif %} 
                                
                        </div>
                            
                        </div>
                    </div>
                
                {% endfor %}

    </div>
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container" style="font-size: 50px; margin-left: 30%; margin-top: 10%;">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h2> Name: {{user.username| capitalize}} </h2>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p style="color: black;"> Bio: {{user.bio}}</p>
    {%else%}
      <p style="color: black;"> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4" style="margin-top: 1%;">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p style="color:black;">No profile picture</p>
    {% endif %}

    {% if user == current_user %}
    <a style="font-size: 40px; text-decoration: none;" href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/random.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="text-align: center; margin-top: 10%;width: 40%;">
    <h2>A Random Quote to Inspire You</h2>
    <div class="card cardquote">
        <div class="card-title">
            <h4 style="text-decoration: underline;">A quote by: <span style="color: rgb(3, 3, 3)">{{quote.author}}</span> </h4>
        </div>
        <p class="card-text" style="width: 80%; margin-left: 10%;">{{quote.quote}}</p>
    </div>
</div>

{% endblock %}